sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: r169oDtc6FGltXNw7/iG9GFc4WVwkZVbIfwmCm/y6r7MQZIL3yXR2w9Eifd+FfR4isD8SW8lgGa9xSNYfRkbPBwYhDeUagJcyCfyMg4sYckZuzkpFQwA2rqMBssQB9YmjMTPA2v+lRZgKtORmVuXF2L+DUJtDDVzUxQjWJ7uTN7pAhipJR0S0UbftlNNkWr9rW4EM32NGL555aBAPaIRduAPcuoi0+ASen/XHZhXpXkzwsgoW24PqZ+f+DXtKW38j9ykN+xyLZHmCh590zzDTlR4XqEkxPpPQa8oAzwTpMBoF+C3cHcHOX+mr5EiCx9gM4tblmgsXJC8kLo4AweugRvYb/OsTkvloPhleP3yMDrsrW3iAjfqiRpMTqRDIu9FwKaXCZLcB205CgTwQOVH5xmp6UUZH/7Zjz0pnQg/ge43xqK1DNvcyM7NJ/n31Vy2gp6bZoYfWqv5qk0HqpwfFjTQNVcJfjwthdRVHbIS3CMGFAccdTM4q+WCJZLQW95mCQxKcAH0GLzaMkrcerkQnGHGWFt2tPhHa3y+Lhjao23F7olrG0IIOX66DjvBMt5DkZ7GeEzx0cjPve+RygAjFUuDLS8RANlQ10+Plb/4kC4joXIPnycchyqt7j8cjGuFXdik+5cuphitMGlDdQI0xJBRGsvL2pdP2qmdqLDbwH4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Napoleon-Bonaparte_3775
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy